version: "3"
services:
    web:
        image: tutum/apache-php
        environment:
            - ALLOW_OVERRIDE=true
        ports:
            - "80:80"
        links:
            - db
        volumes:
            - ./:/app
    db:
        image: mariadb:10.4
        restart: always
        volumes:
        - mariadb-data:/var/lib/mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: bookstore
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        networks:
            - default
        command: mysqld --default-authentication-plugin=mysql_native_password
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
volumes:
    persistent:
    mariadb-data: